<a href="https://colab.research.google.com/github/AydanTrawick/Pytorch-Tut/blob/main/Intro_to_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np

print("Imports ready to go")

Imports ready to go


List

In [4]:
my_list= [[1,2,3,4], [5,6,"apples"]]
my_list

[[1, 2, 3, 4], [5, 6, 'apples']]

Numpy Array

In [17]:
np1= np.random.rand(3,4)
np1

array([[0.97501649, 0.00735957, 0.49730582, 0.80262473],
       [0.443391  , 0.35935251, 0.36750714, 0.75487847],
       [0.60790823, 0.92110993, 0.41501027, 0.20161984]])

Tensors

In [10]:
tensor_2d= torch.randn(3,4)
tensor_2d

tensor([[-1.1306,  1.7103,  0.5158,  0.1787],
        [-0.0585, -1.0107, -0.5485,  1.2817],
        [ 1.7883, -0.5131, -1.0087,  2.0693]])

In [15]:
tensor_3d= torch.zeros(2,4,10)

tensor_3d

tensor([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]])

In [18]:
## Create tensor out of numpy array

my_tensor= torch.tensor(np1)

my_tensor

tensor([[0.9750, 0.0074, 0.4973, 0.8026],
        [0.4434, 0.3594, 0.3675, 0.7549],
        [0.6079, 0.9211, 0.4150, 0.2016]], dtype=torch.float64)