<a href="https://colab.research.google.com/github/AydanTrawick/Pytorch-Tut/blob/main/Tensor_math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np
print("Imports are ready")

Imports are ready


In [16]:
tensor_a= torch.tensor([1,2,3,4])
tensor_b= torch.tensor([5,6,7,8])

In [5]:
# Addition

tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [4]:
# Addition Long Hand

torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [7]:
# Subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [8]:
# Sub function
torch.sub(tensor_b,tensor_a)

tensor([4, 4, 4, 4])

In [9]:
# Multiplication

tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [10]:
# Mul function
torch.mul(tensor_a,tensor_b)

tensor([ 5, 12, 21, 32])

In [11]:
#Division

tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [12]:
# Div function

torch.div(tensor_b,tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [17]:
# Remainder Modulus

tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [18]:
# Remainder Function

torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [19]:
# Exponenets / power

tensor_a ** tensor_b

tensor([    1,    64,  2187, 65536])

In [ ]:
# Exponents function

torch.pow(tensor_a, tensor_b)

In [24]:
# Another way to wright longhand

tensor_add= tensor_a.add(tensor_b)
tensor_sub= tensor_a.sub(tensor_b)


tensor([ 6,  8, 10, 12])

In [25]:
# Reassignment

tensor_a = tensor_a + tensor_b

tensor_a

tensor([ 6,  8, 10, 12])

In [26]:
# Reassignment

tensor_a.add_(tensor_b)

tensor([11, 14, 17, 20])

In [27]:
# New call
tensor_a

tensor([11, 14, 17, 20])