<a href="https://colab.research.google.com/github/AydanTrawick/Pytorch-Tut/blob/main/tensor_ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print("Pytorch is ready")

Pytorch is ready


In [5]:
my_torch= torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
## Reshape and view


my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [14]:
## Reshape if we dont know the number of items we're using

my_torch2 = torch.arange(33)
my_torch2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

In [16]:
my_torch2 = my_torch2.reshape(-1,3)
my_torch2

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29],
        [30, 31, 32]])

In [17]:
my_torch3 = torch.arange(20)
my_torch3

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])

In [19]:
my_torch4= my_torch3.view(2,-1)
my_torch4

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [20]:
# with reshape and view they will update

my_torch5= torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
my_torch6= my_torch5.reshape(2,5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [25]:
my_torch5[1]= 4141
my_torch5[3]= 12
my_torch5


tensor([   0, 4141,    2,   12,    4,    5,    6,    7,    8,    9])

In [26]:
my_torch6

tensor([[   0, 4141,    2,   12,    4],
        [   5,    6,    7,    8,    9]])

In [27]:
# slices

my_torch7= torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
# Grab a specific item
my_torch7[1]

tensor(1)

In [30]:
# Grab a slice

my_torch8= my_torch7.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [34]:
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [36]:
# Return a column

my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])